# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "%FLAVOUR_IMAGE%"


	# Access package generated by `package-for-debian'
	config.vm.synced_folder "%FLAVOUR_DIRECTORY%", "/home/vagrant/flavour"


	# Install package to check if necessary dependencies are downloaded
	# automatically
	#
	# @warning execution currently disabled due to the lack of a useful
	#     testing mode
	config.vm.provision "shell", inline: <<-SHELL
		sudo apt-get update
		sudo apt-get install -y gdebi

		sudo gdebi --non-interactive flavour/violetland_%VIOLETLAND_VERSION%_*.deb
#		violetland
	SHELL

	
end

