# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "debian/jessie64"
	
	config.vm.provision "shell", inline: <<-SHELL
		apt-get update
		apt-get install -y nodejs
		echo "ABC" > /home/vagrant/debian/XYZ
	SHELL

	config.vm.synced_folder ".", "/home/vagrant/debian"
end

