# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "ubuntu/trusty64"


	config.vm.provision "file", source: "../create-orig-tarball/violetland_0.5.orig.tar.gz", destination: "/home/vagrant/violetland_0.5.orig.tar.gz"


	config.vm.provision "shell", inline: <<-SHELL
		sudo apt-get update


		# Install build dependencies
		sudo apt-get install -y build-essential cmake gettext libsdl-ttf2.0-dev libsdl-mixer1.2-dev libsdl-image1.2-dev libboost-all-dev

		# Install Debian package utilities
		sudo apt-get install -y debhelper devscripts gzip tar


		# Unpack upstream sources and add Debian specific files
		tar -xf violetland_0.5.orig.tar.gz
		cp -r /vagrant/debian violetland
		chown -R vagrant:vagrant violetland


		# Build Debian package
		cd violetland
		debuild -us -uc
		cd ..


		# Publish artifacts
		cp violetland_0.5-rc1_amd64.build /vagrant
		cp violetland_0.5-rc1_amd64.changes /vagrant
		cp violetland_0.5-rc1_amd64.deb /vagrant
		cp violetland_0.5-rc1.debian.tar.gz /vagrant
		cp violetland_0.5-rc1.dsc /vagrant

	SHELL

	
end

