# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# Rebuilding everything from scratch takes far too long, therefore we use
	# `mxe-violetland' which provides a preconfigured mxe cross building
	# environment
	config.vm.box = "mxe-violetland-bec5b6c734756f981e98666ec52343277f4fbd2e"
	config.vm.box_url = "file://../../mxe-violetland.box"


	# Access to violetland sources is necessary
	config.vm.synced_folder "../../../..", "/violetland"


	# Copy violetland sources (everything except /violetland/vagrant) to
	# home directory for a local build
	config.vm.provision "shell", inline: <<-SHELL
		apt-get update
		apt-get install -y git rsync zip


		# Copy sources
		rsync -av --progress /violetland /home/vagrant --exclude vagrant
		cd /home/vagrant/violetland


		# Update dependencies
		git submodule init || exit 1
		git submodule update || exit 1


		# Build
		mkdir build-x86
		cd build-x86
		cmake -DCMAKE_TOOLCHAIN_FILE=/home/vagrant/mxe/usr/i686-w64-mingw32.static/share/cmake/mxe-conf.cmake -DCMAKE_INSTALL_PREFIX="../tmp-x86" ".." || exit 1
		make install || exit 1
		cd ..


		# Package
		mkdir windows-x86
		cp "tmp-x86/bin/violetland.exe" "windows-x86" || exit 1
		cp -r tmp-x86/share/violetland/* "windows-x86" || exit 1
		zip -r "violetland-windows-x86.zip" "windows-x86" || exit 1


		# Export to synced folder
		cp "violetland-windows-x86.zip" "/vagrant/"
	SHELL

end

