# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# Rebuilding everything from scratch takes far too long, therefore we use
	# `mxe-violetland' which provides a preconfigured mxe cross building
	# environment
	config.vm.box = "mxe-violetland"
	
	config.vm.provision "shell", inline: <<-SHELL
		apt-get update
		apt-get install -y git zip
	SHELL

	config.vm.provision "file", source: "build-amd64.sh", destination: "build-amd64.sh"
	config.vm.provision "file", source: "build-x86.sh", destination: "build-x86.sh"
	config.vm.synced_folder "../../", "/violetland"
end

